Repository R0merol/Number-Game-v0.1, pull requests merged in 2022-10, with the labels that each got.

#26 Updated README.md file
  README.md
Labels: hacktoberfest-accepted

#27 new logo added
  sprite/number_game.png
Labels: hacktoberfest-accepted

#28 Added 4 achievements
  code/achievement.py
  code/numbergame.py
  code/text.py
  data.json
Labels: polish

#29 Fixed: Error if not launched from root directory
  code/main.py
Labels: clean-up code, hacktoberfest-accepted

#40 Contributors list in README
  README.md
Labels: hacktoberfest-accepted

#41 add requirements.txt and improve installation instructions in README.md
  README.md
  requirements.txt
Labels: hacktoberfest-accepted

#44 improve highscore.py with pathlib and proper use of context manager
  code/highscore.py
Labels: hacktoberfest-accepted

#54 Change the game's icon closes #52
  sprite/number_game.png
Labels: hacktoberfest-accepted
